version: '3.9'

services:
    app:
        container_name: app
        build:
            context: .
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/appdb
            - SPRING_DATASOURCE_USERNAME=test
            - SPRING_DATASOURCE_PASSWORD=testpassw
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            - SPRING_JPA_SHOW_SQL=true
        ports:
            - "8080:8080"

    db:
        container_name: db
        image: postgres:13.4-alpine
        restart: on-failure
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=testpassw 
            - POSTGRES_DB=appdb 