GET http://localhost:8080/ HTTP/1.1

###
POST http://localhost:8080/beer-tap-dispenser/dispenser HTTP/1.1
Content-Type: application/json

{
    "flow_amount":0.080
}

###
PUT http://localhost:8080/beer-tap-dispenser/dispenser/5b402c03-83f6-4bbe-9e53-47856b4ca552/status HTTP/1.1
Content-Type: application/json

{
    "status":"OPEN"
}


###
GET http://localhost:8080/random-uuid HTTP/1.1