GET http://localhost:8080/ HTTP/1.1

###
POST http://localhost:8080/beer-tap-dispenser/dispenser HTTP/1.1
Content-Type: application/json

{
    "flow_amount":0.080
}

###
PUT http://localhost:8080/beer-tap-dispenser/dispenser/f0a231d0-20a7-48d0-937a-5a7508319ad0/status HTTP/1.1
Content-Type: application/json

{
    "status":"OPEN"
}


###
GET http://localhost:8080/random-uuid HTTP/1.1