GET http://localhost:8080/ HTTP/1.1

###
POST http://localhost:8080/beer-tap-dispenser/dispenser HTTP/1.1
Content-Type: application/json

{
    "flow_amount":0.080
}

### crear consumo
PUT http://localhost:8080/beer-tap-dispenser/dispenser/d529bb35-bd5c-4932-a4e4-43222ef801ae/status HTTP/1.1
Content-Type: application/json

{
    "status":""
}

### crear consumo
POST http://localhost:8080/usages HTTP/1.1

### ver los consumos
GET http://localhost:8080/usages HTTP/1.1




















































// summary example response
/*
{
  "amount": 57.678,
  "usages": [
    {
      "opened_at": "2022-01-01T02:00:00Z",
      "closed_at": "2022-01-01T02:00:50Z",
      "flow_volume": 0.064,
      "total_spent": 39.2
    },
    {
      "opened_at": "2022-01-01T02:50:58Z",
      "closed_at": "2022-01-01T02:51:20Z",
      "flow_volume": 0.064,
      "total_spent": 17.248
    },
    {
      "opened_at": "2022-01-01T13:50:58Z",
      "closed_at": null,
      "flow_volume": 0.064,
      "total_spent": 1.23
    }
  ]
}
*/