spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: test
    password: testpassw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
    database: h2
    
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: never
springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /doc/swagger-ui.html
        
