spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    driver-class-name: org.postgresql.Driver
    username: test
    password: testpassw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: never